kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role:  worker
  extraMounts:
  # change this to you preferred local path
  - hostPath: /home/userx/Desktop/geoquery-update
    # no need to change this
    containerPath: /tmp/geoquery-update
- role:  worker
  extraMounts:
  # do the same changes here as above!
  - hostPath: /home/userx/Desktop/geoquery-update
    containerPath: /tmp/geoquery-update
