# Generated by Django 5.2.16 on 2026-07-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # Pinned to the migration that creates each referenced model rather than
    # whatever the leaf happened to be at generation time, so this app is
    # insulated from future branch/merge churn in those apps.
    dependencies = [
        ('analytics', '0001_initial'),   # creates ProcessingOption
        ('datasets', '0001_initial'),    # creates Dataset
        ('features', '0001_initial'),    # creates FeatureCollection
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('datasets', models.ManyToManyField(blank=True, related_name='catalogs', to='datasets.dataset')),
                ('feature_collections', models.ManyToManyField(blank=True, related_name='catalogs', to='features.featurecollection')),
                ('processing_options', models.ManyToManyField(blank=True, related_name='catalogs', to='analytics.processingoption')),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('access_catalog', 'Can access resources in this catalog')],
            },
        ),
    ]
