"""Stats page view.

The stats page is a pre-built HTML snapshot generated by
``analytics.tasks.maintenance.build_stats_report``, a Celery beat task that runs
every 5 minutes and writes to ``settings.STATS_REPORT_PATH``
(default: ``<REQUESTS_DIR>/geoquery_stats.html``).

``stats_view`` serves that file directly -- nothing on the page queries the
database on load. If the file does not exist yet (first boot, before the beat
task has fired), it falls back to a live render so the page is never a 404.

There used to be a ``workers_view`` here, polled every 30s by the page for queue
counts. It ran a GROUP BY over ~280M ``extract_tasks`` rows -- no filter can
prune that table for a global aggregate -- taking ~16s and millions of block
reads per call, which made the page 504 as soon as requests overlapped. Those
counts now come from the same 5-minute report build as the rest of the page.
"""
from pathlib import Path

from django.conf import settings
from django.http import HttpResponse

from stats.builder import StatsBuilder


def stats_view(request):
    path = getattr(
        settings,
        "STATS_REPORT_PATH",
        str(settings.REQUESTS_DIR / "geoquery_stats.html"),
    )
    if Path(path).exists():
        html = Path(path).read_text(encoding="utf-8")
    else:
        html = StatsBuilder().render()
    return HttpResponse(html, content_type="text/html")
