"""Stats page views.

How the stats page stays current
---------------------------------
The page is a pre-built HTML snapshot generated by
``analytics.tasks.maintenance.build_stats_report``, a Celery beat task that
runs every 5 minutes and writes to ``settings.STATS_REPORT_PATH``
(default: ``<REQUESTS_DIR>/geoquery_stats.html``).

``stats_view`` serves that file directly — no DB queries on page load.
If the file does not exist yet (first boot before the beat task has fired),
``StatsBuilder().render()`` falls back to a live render so the page is never
a 404.

``workers_view`` (polled every 5 s by the page's JS) runs two lightweight
COUNT-by-status queries against ``extract_tasks`` and ``requests`` and is
the only live-query path.
"""
import json
from pathlib import Path

from django.conf import settings
from django.db.models import Count
from django.http import HttpResponse, JsonResponse

from stats.builder import StatsBuilder


def stats_view(request):
    path = getattr(
        settings,
        "STATS_REPORT_PATH",
        str(settings.REQUESTS_DIR / "geoquery_stats.html"),
    )
    if Path(path).exists():
        html = Path(path).read_text(encoding="utf-8")
    else:
        html = StatsBuilder().render()
    return HttpResponse(html, content_type="text/html")


def workers_view(request):
    # Status codes: 0=pending, 3=claimed, 2=processing, 1=completed, -1=error
    from analytics.models import ExtractTask, Request

    # Exclude completed (status=1) — there can be tens of millions, and the
    # total is already in the pre-built static page. Only count the in-flight
    # statuses (pending/claimed/processing/error) to keep this fast.
    extract_counts = dict(
        ExtractTask.objects.exclude(status=1)
        .values("status").annotate(n=Count("id")).values_list("status", "n")
    )
    request_counts = dict(
        Request.objects.values("status").annotate(n=Count("id")).values_list("status", "n")
    )

    return JsonResponse({
        "queues": {
            "extract_pending": extract_counts.get(0, 0),
            "extract_claimed": extract_counts.get(3, 0),
            "extract_processing": extract_counts.get(2, 0),
            "extract_error": extract_counts.get(-1, 0),
            "requests_queued": request_counts.get(-1, 0),
            "requests_processing": request_counts.get(0, 0) + request_counts.get(2, 0),
        },
    })
