# Generated by Django 5.2.6 on 2025-12-16 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('prepare_time', models.DateTimeField(blank=True, null=True)),
                ('process_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'requests',
            },
        ),
        migrations.CreateModel(
            name='ExtractTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(default=0)),
                ('priority', models.IntegerField(default=0)),
                ('submit_time', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('complete_time', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=100, null=True)),
                ('kwargs', models.JSONField(blank=True, null=True)),
                ('fm', models.ForeignKey(db_column='fm_id', on_delete=django.db.models.deletion.CASCADE, to='features.featmap')),
                ('resource', models.ForeignKey(db_column='resource_id', on_delete=django.db.models.deletion.CASCADE, to='datasets.datasetresource')),
            ],
            options={
                'db_table': 'extract_tasks',
            },
        ),
        migrations.CreateModel(
            name='ExtractData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('data_column', models.CharField(blank=True, max_length=100, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('str_value', models.CharField(blank=True, max_length=100, null=True)),
                ('extract_task', models.ForeignKey(db_column='extract_task_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.extracttask')),
            ],
            options={
                'db_table': 'extract_data',
            },
        ),
        migrations.CreateModel(
            name='ProcessingOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('function', models.CharField(max_length=100)),
                ('result_type', models.CharField(blank=True, max_length=100, null=True)),
                ('kwargs', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, related_name='processing_options', to='datasets.dataset')),
            ],
            options={
                'db_table': 'processing_options',
            },
        ),
        migrations.AddField(
            model_name='extracttask',
            name='po',
            field=models.ForeignKey(db_column='po_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.processingoption'),
        ),
        migrations.CreateModel(
            name='RequestMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(db_column='req_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.request')),
                ('task', models.ForeignKey(db_column='task_id', on_delete=django.db.models.deletion.CASCADE, to='analytics.extracttask')),
            ],
            options={
                'db_table': 'request_map',
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('dataset', models.ForeignKey(db_column='dataset_id', on_delete=django.db.models.deletion.CASCADE, to='datasets.dataset')),
                ('geom', models.ForeignKey(db_column='geom_id', on_delete=django.db.models.deletion.CASCADE, to='features.feature')),
            ],
            options={
                'db_table': 'coverage',
                'constraints': [models.UniqueConstraint(fields=('geom', 'dataset'), name='coverage_geom_dataset_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='processingoption',
            constraint=models.UniqueConstraint(fields=('dataset', 'function', 'kwargs'), name='processing_options_dataset_function_kwargs_unique'),
        ),
        migrations.AddConstraint(
            model_name='processingoption',
            constraint=models.UniqueConstraint(fields=('dataset', 'short_name', 'active'), name='processing_options_dataset_short_name_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='extracttask',
            constraint=models.UniqueConstraint(fields=('resource', 'fm', 'po'), name='extract_tasks_resource_fm_po_pk'),
        ),
        migrations.AddConstraint(
            model_name='extracttask',
            constraint=models.UniqueConstraint(fields=('id',), name='extract_tasks_id_unique'),
        ),
    ]
