# Generated by Django 6.0.2 on 2026-05-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comments_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='contact_flag',
            field=models.BooleanField(default=False),
        ),
    ]
