# Generated by Django 6.0.2 on 2026-05-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_request_data_jsonfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='date',
        ),
    ]
