# Generated by Django 5.2.15 on 2026-07-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_extracttask_kwargs_uniqueness'),
    ]

    operations = [
        # Constraint was already dropped by 0009 via RunSQL; update state only.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveConstraint(
                    model_name='extracttask',
                    name='extract_tasks_resource_fm_po_pk',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='extractdata',
            name='int_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        # State-only: requesttoken.id is already an int PK in the DB; no column change needed.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='requesttoken',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                ),
            ],
            database_operations=[],
        ),
    ]
