# Generated by Django 5.2.15 on 2026-07-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0011_extracttask_kwargs_index_md5'),
        ('analytics', '0011_request_user_request_requests_contact_lower_idx'),
    ]

    operations = [
    ]
