from django.db import migrations, models


# Column list/types below were verified against the live scratch DB schema
# (\d extract_tasks / \d extract_data) rather than assumed from the model
# declarations:
#   - extract_tasks.id is a plain (32-bit) identity column -- ExtractTask
#     explicitly declares `id = models.AutoField(primary_key=True)`.
#   - extract_data.id must be BIGINT: ExtractData does not declare an
#     explicit id field, so it picks up the project's
#     DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField" (see
#     geoquery/settings.py), and the live column is
#     "bigint ... generated by default as identity".
#   - status/priority/attempts/submit_time carry NOT NULL with NO db-level
#     default in the live schema -- their Python-side defaults
#     (default=0 / auto_now_add=True) are applied by Django in the INSERT
#     itself, not via a DB DEFAULT clause. Adding DEFAULT 0 / DEFAULT NOW()
#     here would be a schema drift from what Django actually manages.
#   - fm_id/po_id FKs carry no ON DELETE clause in the live schema, even
#     though the model uses on_delete=models.CASCADE: Django's
#     on_delete=CASCADE is enforced at the ORM/Collector level, not as a
#     DB-level ON DELETE CASCADE action, for FKs generated by normal
#     Django migrations. All FK constraints in this schema are also
#     DEFERRABLE INITIALLY DEFERRED (Django's Postgres backend default) --
#     both conventions are replicated below for consistency.
_DROP_AND_RECREATE_PARTITIONED = """
    -- extract_tasks and extract_data were truncated in migration 0017;
    -- dropping and recreating as partitioned tables is safe -- there is no
    -- data to preserve, and Postgres cannot ALTER an existing table into a
    -- partitioned one in place.
    DROP TABLE IF EXISTS extract_data CASCADE;
    DROP TABLE IF EXISTS extract_tasks CASCADE;

    CREATE TABLE extract_tasks (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        resource_ids INTEGER[] NOT NULL,
        dataset_id INTEGER NOT NULL,
        task_group_period VARCHAR(10),
        fm_id INTEGER NOT NULL REFERENCES feat_map(id) DEFERRABLE INITIALLY DEFERRED,
        po_id INTEGER NOT NULL REFERENCES processing_options(id) DEFERRABLE INITIALLY DEFERRED,
        status INTEGER NOT NULL,
        priority INTEGER NOT NULL,
        submit_time TIMESTAMPTZ NOT NULL,
        start_time TIMESTAMPTZ,
        update_time TIMESTAMPTZ,
        complete_time TIMESTAMPTZ,
        attempts INTEGER NOT NULL,
        error VARCHAR(100),
        kwargs JSONB,
        PRIMARY KEY (dataset_id, id)
    ) PARTITION BY LIST (dataset_id);

    CREATE TABLE extract_data (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        extract_task_id INTEGER NOT NULL,
        dataset_id INTEGER NOT NULL,
        name VARCHAR(100),
        data_column VARCHAR(100),
        float_values FLOAT8[],
        int_values BIGINT[],
        str_values VARCHAR(100)[],
        PRIMARY KEY (dataset_id, id)
    ) PARTITION BY LIST (dataset_id);
"""

# Catch-all so a dataset_id that doesn't have its own partition yet (a
# dataset created after this migration ran, before anything gives it its
# own partition) still has somewhere to land instead of every insert
# failing outright. There is currently no mechanism anywhere in the
# codebase that creates a new per-dataset partition when a Dataset row is
# created -- rows for any dataset added post-migration will stay in this
# DEFAULT partition indefinitely unless/until that's built.
_CREATE_DEFAULT_PARTITIONS = """
    CREATE TABLE extract_tasks_default PARTITION OF extract_tasks DEFAULT;
    CREATE TABLE extract_data_default PARTITION OF extract_data DEFAULT;
"""

# Django auto-creates a btree index on every ForeignKey column
# (db_index=True is the default); the raw CREATE TABLE above only defines
# the PK, so these need recreating by hand to restore parity with what
# existed pre-partitioning. Declared on the partitioned parent, not
# per-partition -- Postgres 11+ propagates a parent index automatically to
# every current and future partition.
_CREATE_FK_INDEXES = """
    CREATE INDEX extract_tasks_fm_id_idx ON extract_tasks (fm_id);
    CREATE INDEX extract_tasks_po_id_idx ON extract_tasks (po_id);
    CREATE INDEX extract_data_extract_task_id_idx ON extract_data (extract_task_id);
"""

_REVERSE = """
    DROP TABLE IF EXISTS extract_data CASCADE;
    DROP TABLE IF EXISTS extract_tasks CASCADE;
"""


def _create_per_dataset_partitions(apps, schema_editor):
    Dataset = apps.get_model("datasets", "Dataset")
    # Deliberately not filtered to active=True: an inactive dataset can
    # still have historical extract_tasks/extract_data rows that need a
    # home, and giving every dataset a partition up front is cheap (an
    # empty partition costs essentially nothing) compared to the
    # complexity of creating one lazily when a dataset is reactivated.
    with schema_editor.connection.cursor() as cursor:
        for dataset_id in Dataset.objects.values_list("id", flat=True):
            cursor.execute(
                f"""
                CREATE TABLE extract_tasks_ds_{dataset_id}
                    PARTITION OF extract_tasks FOR VALUES IN ({dataset_id});
                CREATE TABLE extract_data_ds_{dataset_id}
                    PARTITION OF extract_data FOR VALUES IN ({dataset_id});
                """
            )


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    """
    Converts extract_tasks/extract_data to LIST partitions on dataset_id.

    SAFE ONLY BECAUSE THESE TABLES ARE EMPTY: migration 0017 already
    TRUNCATEs both, which is what makes a DROP TABLE + CREATE TABLE
    ... PARTITION BY rewrite acceptable here -- there is no data to lose.
    Postgres cannot ALTER an existing table into a partitioned one in
    place, so this pattern is the only option for converting a live,
    populated table into a partitioned one; anyone reusing this migration
    as a template against a table that still has real rows needs a proper
    backfill (create the partitioned table under a new name, copy data
    across, swap), not a straight copy of this file.
    """

    dependencies = [
        ("analytics", "0020_extracttaskbuildprogress_resource_ids"),
        ("datasets", "0008_dataset_task_group_period"),
    ]

    operations = [
        migrations.RunSQL(
            sql=_DROP_AND_RECREATE_PARTITIONED + _CREATE_DEFAULT_PARTITIONS,
            reverse_sql=_REVERSE,
        ),
        migrations.RunPython(_create_per_dataset_partitions, _noop_reverse),
        migrations.RunSQL(
            sql=_CREATE_FK_INDEXES,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE extract_data
                    ADD CONSTRAINT extract_data_extract_task_fk
                    FOREIGN KEY (dataset_id, extract_task_id)
                    REFERENCES extract_tasks (dataset_id, id)
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="""
                ALTER TABLE request_map ADD COLUMN dataset_id INTEGER;
                -- request_map is also truncated (migration 0017), so no
                -- backfill is needed for the NOT NULL below.
                ALTER TABLE request_map ALTER COLUMN dataset_id SET NOT NULL;
                -- Defensive no-op in practice: the DROP TABLE ... CASCADE on
                -- extract_tasks earlier in this migration already cascaded
                -- this constraint away. IF EXISTS makes it safe either way.
                ALTER TABLE request_map DROP CONSTRAINT IF EXISTS request_map_task_id_08f7ae9f_fk_extract_tasks_id;
                ALTER TABLE request_map
                    ADD CONSTRAINT request_map_extract_task_fk
                    FOREIGN KEY (dataset_id, task_id)
                    REFERENCES extract_tasks (dataset_id, id)
                    DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
                ALTER TABLE request_map DROP CONSTRAINT IF EXISTS request_map_extract_task_fk;
                ALTER TABLE request_map DROP COLUMN IF EXISTS dataset_id;
            """,
            # Keep Django's model state in sync with the RequestMap.dataset_id
            # field added in models.py -- without this, `makemigrations`
            # would detect drift and generate a follow-up AddField migration
            # for a column that already exists, which would fail outright
            # (Django's AddField has no IF NOT EXISTS) if anyone ran it.
            state_operations=[
                migrations.AddField(
                    model_name="requestmap",
                    name="dataset_id",
                    field=models.IntegerField(),
                ),
            ],
        ),
    ]
