# Generated by Django 5.2.17 on 2026-09-22 20:06

from django.db import migrations, models


# Reconciles model drift, not a behaviour change. settings.DEFAULT_AUTO_FIELD is
# BigAutoField, but this table was created before that applied to it, so its id
# is still a plain integer. Django therefore re-detected the difference on every
# makemigrations run and warned that models had unapplied changes.
#
# Worth clearing rather than living with: an unreconciled difference is silently
# bundled into the *next* migration anyone generates, so an unrelated change
# ends up carrying a table rewrite nobody asked for.
#
# Cheap here. The SQL is one `ALTER COLUMN id TYPE bigint`, which rewrites the
# table under ACCESS EXCLUSIVE -- but extract_task_build_progress holds one row
# per (resource_ids, po) unit of work, currently 2,752. Nothing references this
# id as a foreign key. build_extract_tasks writes claimed_at here, and will
# block for the duration of the rewrite; its transactions against this table are
# short (the long ones are INSERTs into extract_tasks), so the lock should be
# acquired and released promptly.


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_extracttask_pending_idx_id_tiebreaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extracttaskbuildprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
