# Generated by Django 5.2.17 on 2026-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0025_extracttask_pending_idx_id_tiebreaker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtractTaskBuildRun',
        ),
        migrations.AlterField(
            model_name='extracttaskbuildprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
