# Generated by Django 5.2.17 on 2026-10-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0029_extract_tasks_sweep_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='extracttaskbuildrun',
            name='run_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extracttaskbuildrun',
            name='workers_remaining',
            field=models.PositiveIntegerField(db_default=0, default=0),
        ),
    ]
