# Generated by Django 5.2.17 on 2026-10-07 20:52

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0030_extracttaskbuildrun_worker_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyRequest',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('contact', models.CharField(max_length=100)),
                ('custom_name', models.CharField(max_length=100)),
                ('submit_time', models.DateTimeField()),
                ('complete_time', models.DateTimeField()),
                ('boundary_title', models.CharField(max_length=100)),
                ('boundary_name', models.CharField(max_length=64)),
                ('boundary_group', models.CharField(max_length=32)),
                ('dataset_titles', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=list, size=None)),
                ('dataset_count', models.SmallIntegerField(default=0)),
                ('data', models.JSONField()),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legacy_requests',
                'indexes': [models.Index(django.db.models.functions.text.Lower('contact'), name='legacy_contact_lower_idx'), models.Index(fields=['-submit_time'], name='legacy_submit_time_idx')],
            },
        ),
    ]
