{
 "title": "GeoQuery Backend",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Tasks In Processing Queue",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM extract_tasks WHERE status = 0;"
    }
   ]
  },
  {
   "title": "Tasks Completed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM extract_tasks WHERE status = 1;"
    }
   ]
  },
  {
   "title": "Oldest Incomplete Request",
   "type": "gauge",
   "description": "Age of oldest incomplete GeoQuery request",
   "gridPos": { "h": 6, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT (EXTRACT(EPOCH FROM current_timestamp - submit_time)/3600)::Integer AS hours FROM requests WHERE complete_time IS NULL ORDER BY submit_time ASC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Requests, last 30 days",
   "type": "timeseries",
   "description": "Number of requests submitted per day over the last 30 days",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  search_date,\n  COUNT(requests.id) AS request_count\nFROM\n  (\n    SELECT\n      DATE(now()) - sequential_dates AS search_date\n    FROM\n      generate_series(29, 0, -1) AS sequential_dates\n  )\nLEFT JOIN requests ON DATE(requests.submit_time) = search_date\n\nGROUP BY search_date\nORDER BY search_date asc;"
    }
   ]
  },
  {
   "title": "Errors, Last 7 Days",
   "type": "logs",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{level=\"CRITICAL\"}",
     "maxLines": 1000
    },
    {
     "expr": "{level=\"ERROR\"} |= ``",
     "maxLines": 1000
    }
   ]
  }
 ]
}