"""
Django settings for geoquery project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes", "on")
if not DEBUG:
    DEBUG = True

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    print("WARNING: DJANGO_SECRET_KEY not set; using insecure default key. "
        "This is only safe for local development. Set DJANGO_SECRET_KEY in production.")
    print("DEBUG status:", DEBUG)
    if DEBUG:
        print("DEBUG is on; using insecure default key.")
        SECRET_KEY = (
            "django-insecure-(5al+g1afse8_v9fhhwv1m&wslqe31x(fz_!&wdn557r9y3@as"
        )
    else:
        raise RuntimeError("DJANGO_SECRET_KEY must be set when DEBUG is off")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Behind Cloudflare Tunnel (and any TLS-terminating proxy) the origin is reached
# over plain HTTP, so request.is_secure() is False unless we trust the
# X-Forwarded-Proto header that the tunnel forwards. Without this, Django's CSRF
# check builds an "http://…" origin that never matches the browser's "https://…"
# Origin header, so admin login POSTs fail with "Origin checking failed".
# Safe here because the origin is only reachable through the tunnel, so a client
# cannot spoof this header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Origins Django trusts for unsafe (POST) requests; each must include the scheme.
# Required since Django 4.0 for HTTPS-behind-proxy POSTs such as the admin login.
# Set DJANGO_CSRF_TRUSTED_ORIGINS in production, e.g. "https://geoquery.org".
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]

# Prometheus metrics (disabled by default)
PROMETHEUS_ENABLED = os.getenv("PROMETHEUS_ENABLED", "False").lower() in (
    "true",
    "1",
    "yes",
)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django.contrib.postgres",
    "rest_framework",
    "corsheaders",
    "django_celery_results",
    "geoquery",
    "features",
    "datasets",
    "analytics",
    "visualize",
]

if PROMETHEUS_ENABLED:
    INSTALLED_APPS.insert(0, "django_prometheus")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "geoquery.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "geoquery.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django_prometheus.db.backends.postgis"
        if PROMETHEUS_ENABLED
        else "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("PG_DBNAME", "geoquery"),
        "USER": os.getenv("PG_USER", "django_user"),
        "PASSWORD": os.getenv("PG_PASSWORD", ""),
        "HOST": os.getenv("PG_HOST", "localhost"),
        "PORT": os.getenv("PG_PORT", "5432"),
        "OPTIONS": {
            "sslmode": os.getenv("PG_SSL_MODE", "prefer"),
        },
        "CONN_MAX_AGE": 0,  # New connection per request
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Where `collectstatic` gathers files for WhiteNoise to serve in production.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves admin/static files directly from Django (no separate web
# server needed) and compresses + hashes them for caching.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite's default dev server
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

# Results
RESULTS_DIR = Path(os.environ.get("RESULTS_DIR", str(BASE_DIR.parent / "results")))
ASSETS_DIR = Path(os.environ.get("ASSETS_DIR", str(BASE_DIR.parent / "assets")))
DOCS_DIR = Path(os.environ.get("DOCS_DIR", str(BASE_DIR.parent / "docs")))
DOWNLOAD_BASE_URL = os.environ.get("DOWNLOAD_BASE_URL", "http://localhost:8000")
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:5173")
TOKEN_EXPIRY_MONTHS = int(os.environ.get("TOKEN_EXPIRY_MONTHS", "6"))

# Protomaps
PROTOMAPS_API_KEY = os.environ.get("PROTOMAPS_API_KEY", "")

# Notebook export (GitHub token scoped to `gist` only)
GITHUB_GIST_TOKEN = os.environ.get("GITHUB_GIST_TOKEN", "")
# How long a Colab export gist lives before the cleanup sweep removes it.
# Long enough for Colab to load the notebook and the user to "Save a copy".
EXPORT_GIST_TTL_SECONDS = int(os.environ.get("EXPORT_GIST_TTL_SECONDS", "3600"))

# Celery
CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL", "amqp://guest:guest@localhost:5672//"
)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "django-db")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

# Two-queue split: only the raster extract task (which needs /data) runs on the
# "processing" queue; everything else (coverage, docs, beat/maintenance) defaults
# to "background". New tasks fail safe onto background unless explicitly routed.
CELERY_TASK_DEFAULT_QUEUE = "background"
CELERY_TASK_ROUTES = {
    "analytics.tasks.processing.run_extract_task": {"queue": "processing"},
}

STALE_TASK_MINUTES = int(os.environ.get("STALE_TASK_MINUTES", "30"))
CELERY_BEAT_SCHEDULE = {
    "free-stale-processing-tasks": {
        "task": "analytics.tasks.maintenance.free_stale_processing_tasks",
        "schedule": 3600,
    },
    "manage-processing-task-errors": {
        "task": "analytics.tasks.maintenance.manage_processing_task_errors",
        "schedule": 3600,
    },
    "build-dataset-docs": {
        "task": "datasets.tasks.build_dataset_docs_task",
        "schedule": crontab(hour=2, minute=0),
    },
    "build-boundary-docs": {
        "task": "features.tasks.build_boundary_docs_task",
        "schedule": crontab(hour=2, minute=15),
    },
    "dispatch-processing-tasks": {
        "task": "analytics.tasks.maintenance.dispatch_processing_tasks",
        "schedule": crontab(minute="0,5,10,15,20,25,30,35,40,45,50,55"),
    },
    "process-user-requests": {
        "task": "analytics.tasks.maintenance.process_user_requests",
        "schedule": crontab(minute="2,7,12,17,22,27,32,37,42,47,52,57"),
    },
    "build-stats-report": {
        "task": "analytics.tasks.maintenance.build_stats_report",
        "schedule": 3600,
    },
    "sweep-coverage-records": {
        "task": "analytics.tasks.maintenance.sweep_coverage_records",
        "schedule": crontab(hour=3, minute=0),
    },
    "build-extract-tasks": {
        "task": "analytics.tasks.maintenance.build_extract_tasks",
        "schedule": crontab(hour=3, minute=30),
    },
    "run-user-outreach": {
        "task": "analytics.tasks.maintenance.run_user_outreach",
        "schedule": crontab(hour=6, minute=0, day_of_week=2),
    },
    "sweep-export-gists": {
        "task": "visualize.tasks.sweep_export_gists",
        "schedule": 3600,
    },
}

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "request_token": os.environ.get("THROTTLE_RATE_REQUEST_TOKEN", "10/hour"),
        "request_submit": os.environ.get("THROTTLE_RATE_REQUEST_SUBMIT", "60/hour"),
    },
}
