"""
Django settings for geoquery project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in ("true", "1", "yes", "on")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    print(
        "WARNING: DJANGO_SECRET_KEY not set; using insecure default key. "
        "This is only safe for local development. Set DJANGO_SECRET_KEY in production."
    )
    print("DEBUG status:", DEBUG)
    if DEBUG:
        print("DEBUG is on; using insecure default key.")
        SECRET_KEY = (
            "django-insecure-(5al+g1afse8_v9fhhwv1m&wslqe31x(fz_!&wdn557r9y3@as"
        )
    else:
        raise RuntimeError("DJANGO_SECRET_KEY must be set when DEBUG is off")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

# Behind Cloudflare Tunnel (and any TLS-terminating proxy) the origin is reached
# over plain HTTP, so request.is_secure() is False unless we trust the
# X-Forwarded-Proto header that the tunnel forwards. Without this, Django's CSRF
# check builds an "http://…" origin that never matches the browser's "https://…"
# Origin header, so admin login POSTs fail with "Origin checking failed".
# Safe here because the origin is only reachable through the tunnel, so a client
# cannot spoof this header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_PORT = True

# Origins Django trusts for unsafe (POST) requests; each must include the scheme.
# Required since Django 4.0 for HTTPS-behind-proxy POSTs such as the admin login.
# Set DJANGO_CSRF_TRUSTED_ORIGINS in production, e.g. "https://geoquery.org".
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if origin.strip()
]
# In dev the Vite proxy rewrites the Host header (changeOrigin), so unsafe
# requests arrive with Origin http://localhost:5173 but Host localhost:8000
# and would fail Django's CSRF origin check without this.
if DEBUG and not CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8000",
    ]

# Prometheus metrics (disabled by default)
PROMETHEUS_ENABLED = os.getenv("PROMETHEUS_ENABLED", "False").lower() in (
    "true",
    "1",
    "yes",
)

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "django.contrib.postgres",
    "rest_framework",
    "drf_spectacular",
    "corsheaders",
    "django_celery_results",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.github",
    "allauth.headless",
    # GeoQuery's own OpenID Connect provider, mounted at /api/idp/. Its one
    # client is the MCP server (see mcp_server.auth), so chat clients sign in
    # as the same accounts.User the website uses. The app label is
    # `allauth_idp_oidc`; `allauth.idp` itself has no AppConfig and must not
    # be listed.
    "allauth.idp.oidc",
    "guardian",
    "geoquery",
    "accounts",
    "features",
    "datasets",
    "analytics",
    "catalog",
    "visualize",
    "public_api",
    "stac_api",
    "mcp_server",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if PROMETHEUS_ENABLED:
    INSTALLED_APPS.insert(0, "django_prometheus")
    # The Before/After pair must wrap the whole stack so request latency
    # covers every other middleware.
    MIDDLEWARE = (
        ["django_prometheus.middleware.PrometheusBeforeMiddleware"]
        + MIDDLEWARE
        + ["django_prometheus.middleware.PrometheusAfterMiddleware"]
    )
    # Metrics are served by a standalone exporter thread on this port rather
    # than through Django's URLconf, so /metrics is never reachable via the
    # app port (and thus never public), and scrapes bypass ALLOWED_HOSTS.
    # The thread binds once per process: the server must run exactly one
    # Django process per container (uvicorn without --workers).
    PROMETHEUS_METRICS_EXPORT_PORT = int(os.getenv("PROMETHEUS_METRICS_PORT", "9091"))
    # The library's default bind address is "", which getaddrinfo rejects on
    # some systems; bind the wildcard address explicitly.
    PROMETHEUS_METRICS_EXPORT_ADDRESS = "0.0.0.0"

# Extract worker metrics (analytics.metrics), served by run_extract_worker's
# parent process on this port. Separate from PROMETHEUS_ENABLED, which is the
# API server's middleware and DB instrumentation: the worker exporter needs
# PROMETHEUS_MULTIPROC_DIR set in the environment as well, because its tasks
# run in child processes whose metrics only reach the parent through files.
# 0 disables it.
WORKER_METRICS_PORT = int(os.getenv("WORKER_METRICS_PORT", "0"))

ROOT_URLCONF = "geoquery.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        # Project-level overrides win over app templates. Used to restyle the
        # few pages allauth renders server-side (the OIDC consent screen the
        # MCP sign-in flow lands on); allauth's own templates are unstyled.
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "geoquery.context_processors.frontend",
            ],
        },
    },
]

WSGI_APPLICATION = "geoquery.wsgi.application"

def _pg(prefix, fallback=None):
    """Build a database config from ``<prefix>_*`` env vars.

    Two prefixes are in play in the cluster: ``PG_RW_*`` points at the
    read/write pgBouncer, ``PG_RO_*`` at the read-only one in front of the
    standbys. Only the backend and background-worker pods are given
    ``PG_RO_*``; processing workers, beat, ingest and the migration Job get
    ``PG_RW_*`` alone, so ``fallback`` is what
    keeps a stray ``.using("replica")`` in those processes pointing at the
    primary instead of crashing on startup.
    """

    def env(suffix, default):
        val = os.getenv(f"{prefix}_{suffix}")
        if val is None and fallback:
            val = os.getenv(f"{fallback}_{suffix}")
        return default if val is None else val

    return {
        "ENGINE": "django_prometheus.db.backends.postgis"
        if PROMETHEUS_ENABLED
        else "django.contrib.gis.db.backends.postgis",
        "NAME": env("DBNAME", "geoquery"),
        "USER": env("USER", "django_user"),
        "PASSWORD": env("PASSWORD", ""),
        "HOST": env("HOST", "localhost"),
        "PORT": env("PORT", "5432"),
        "OPTIONS": {
            "sslmode": os.getenv("PG_SSL_MODE", "prefer"),
        },
        "CONN_MAX_AGE": 0,  # New connection per request; pgBouncer holds the pool
        # Server-side cursors are connection-local, so they break under
        # pgBouncer's transaction pooling. Django falls back to a client-side
        # fetch. Load-bearing for the .iterator() in
        # accounts/management/commands/backfill_request_claims.py.
        "DISABLE_SERVER_SIDE_CURSORS": True,
    }


# Do NOT add "TIME_ZONE" here: Django raises ImproperlyConfigured for
# PostgreSQL when USE_TZ is True. The CloudNativePG Cluster sets the server's
# timezone to UTC instead, which stops Django emitting a SET TIME ZONE on
# every connection.
DATABASES = {
    "default": _pg("PG_RW"),
    "replica": {**_pg("PG_RO", fallback="PG_RW"), "TEST": {"MIRROR": "default"}},
}

DATABASE_ROUTERS = ["geoquery.dbrouter.ReadReplicaRouter"]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Cache. The OIDC provider keeps authorization codes here for the 60 seconds
# between /authorize and /token (allauth.idp.oidc), so this must be shared
# across backend replicas -- the in-memory default would hand a code to one
# process and look it up in another. The table is created by
# `manage.py createcachetable`, which deployments run right after `migrate`.
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Where `collectstatic` gathers files for WhiteNoise to serve in production.
STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise serves admin/static files directly from Django (no separate web
# server needed) and compresses + hashes them for caching.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings for development
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Vite's default dev server
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

# Exclude stac_api from corsheaders' handling — it needs an unconditional
# wildcard Access-Control-Allow-Origin (see StacApiBaseMixin), but
# corsheaders' allowlist-based CORS_ALLOWED_ORIGINS doesn't support that,
# and worse, its middleware intercepts preflight OPTIONS requests before
# they reach the view, bypassing StacApiBaseMixin.finalize_response()
# entirely. Scoping corsheaders off this path lets stac_api handle its
# own CORS end-to-end instead.
CORS_URLS_REGEX = r"^(?!/api/stac/).*$"

# Results
REQUESTS_DIR = Path(os.environ.get("REQUESTS_DIR", str(BASE_DIR.parent / "requests")))
ASSETS_DIR = Path(os.environ.get("ASSETS_DIR", str(BASE_DIR.parent / "assets")))
DOCS_DIR = Path(os.environ.get("DOCS_DIR", str(BASE_DIR.parent / "docs")))
DOWNLOAD_BASE_URL = os.environ.get("DOWNLOAD_BASE_URL", "http://localhost:8000")
FRONTEND_BASE_URL = os.environ.get("FRONTEND_BASE_URL", "http://localhost:5173")
TOKEN_EXPIRY_MONTHS = int(os.environ.get("TOKEN_EXPIRY_MONTHS", "6"))

# Authentication (django-allauth, headless mode for the SPA)
AUTH_USER_MODEL = "accounts.User"

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # admin login
    "allauth.account.auth_backends.AuthenticationBackend",
    # Object permissions on Catalog (see the catalog app). Not used by
    # catalog.access, which calls get_objects_for_user directly, but without it
    # `manage.py check` raises guardian.W001 and user.has_perm(perm, obj)
    # silently returns False in the admin and templates.
    "guardian.backends.ObjectPermissionBackend",
]

# No phantom anonymous User row: accounts.User has a unique, required email and
# is managed by allauth, so guardian's post_migrate receiver would insert a row
# that collides with the next blank-email user. Setting this to None disables
# that receiver -- it is read at import time, so it must be in place before the
# first migrate with guardian installed. Anonymous callers are short-circuited
# in catalog.access before guardian is ever consulted, because guardian's own
# None guard covers only the has_perm path, not get_objects_for_user.
ANONYMOUS_USER_NAME = None

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
# Multi-email (add + verify secondary addresses) is how users claim historical
# requests submitted under other emails. ACCOUNT_CHANGE_EMAIL must stay False:
# enabling it silently deletes secondary EmailAddress rows.
ACCOUNT_CHANGE_EMAIL = False
ACCOUNT_MAX_EMAIL_ADDRESSES = 5
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[GeoQuery] "
ACCOUNT_ADAPTER = "accounts.adapter.AccountAdapter"
SOCIALACCOUNT_ADAPTER = "accounts.adapter.SocialAccountAdapter"

SOCIALACCOUNT_PROVIDERS = {
    "github": {
        "APP": {
            "client_id": os.environ.get("GITHUB_OAUTH_CLIENT_ID", ""),
            "secret": os.environ.get("GITHUB_OAUTH_CLIENT_SECRET", ""),
        },
        # user:email is required to fetch verified addresses when the user's
        # profile email is private.
        "SCOPE": ["read:user", "user:email"],
    }
}
SOCIALACCOUNT_QUERY_EMAIL = True
# A GitHub login whose verified email already belongs to an existing account
# logs into that account instead of creating a duplicate.
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True
SOCIALACCOUNT_STORE_TOKENS = False

HEADLESS_ONLY = True
HEADLESS_SERVE_SPECIFICATION = DEBUG
HEADLESS_FRONTEND_URLS = {
    "account_confirm_email": f"{FRONTEND_BASE_URL}/account/verify-email/{{key}}",
    "account_reset_password_from_key": f"{FRONTEND_BASE_URL}/account/password-reset/{{key}}",
    "account_signup": f"{FRONTEND_BASE_URL}/account",
    "socialaccount_login_error": f"{FRONTEND_BASE_URL}/account/provider/callback",
}

# Where `login_required` sends an unauthenticated browser. It matters here
# because allauth's OIDC /authorize view is the one server-rendered page a
# normal user can land on: a chat client connecting to the MCP server follows
# a redirect to /api/idp/identity/o/authorize, and if there is no session yet
# this is where they end up. Django treats LOGIN_URL as an opaque string, so
# pointing it at the SPA (cross-origin in development) works -- the page reads
# the `next` it is given and returns the browser there after sign-in.
LOGIN_URL = f"{FRONTEND_BASE_URL.rstrip('/')}/account"

# ── OpenID Connect provider (allauth.idp.oidc, mounted at /api/idp/) ─────────
# GeoQuery signs its own MCP users in rather than sending them to GitHub a
# second time: the website remains the only place an upstream provider is
# configured, and the MCP server is just an OAuth client of this provider.

# RSA private key (PEM) that signs ID tokens and JWT access tokens. Optional
# at import time on purpose -- the deployment's migration Job runs
# `ensure_mcp_oidc_client` without it, and Django must still start.
IDP_OIDC_PRIVATE_KEY = os.environ.get("OIDC_PRIVATE_KEY", "")

# Opaque (the default) would force the MCP server to call userinfo or
# introspection on every request. JWT access tokens are verified offline
# against the JWKS endpoint instead.
IDP_OIDC_ACCESS_TOKEN_FORMAT = "jwt"

# Pins `iss` to a fixed public value; see accounts.oidc for why.
IDP_OIDC_ADAPTER = "accounts.oidc.GeoQueryOIDCAdapter"

# Email (Django's framework; allauth verification mail sends through this).
# Dev default prints emails to the backend container log.
EMAIL_BACKEND = os.environ.get(
    "DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend"
    if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "noreply@aiddata.wm.edu"
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_PASSWORD", "")
DEFAULT_FROM_EMAIL = "AidData GeoQuery <geoquery@aiddata.wm.edu>"

# Protomaps
PROTOMAPS_API_KEY = os.environ.get("PROTOMAPS_API_KEY", "")

# Notebook export (GitHub token scoped to `gist` only)
GITHUB_GIST_TOKEN = os.environ.get("GITHUB_GIST_TOKEN", "")
# How long a Colab export gist lives before the cleanup sweep removes it.
# Long enough for Colab to load the notebook and the user to "Save a copy".
EXPORT_GIST_TTL_SECONDS = int(os.environ.get("EXPORT_GIST_TTL_SECONDS", "3600"))

# Celery
CELERY_BROKER_URL = os.environ.get(
    "CELERY_BROKER_URL", "amqp://guest:guest@localhost:5672//"
)
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "django-db")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
# Results are written for every task that does not opt out, and nothing ever
# pruned them: celery.backend_cleanup was not in the beat schedule, so the
# table had grown to 2.8M rows / 4.4GB in 43 hours with no upper bound. The
# cleanup task only runs if it is scheduled (see CELERY_BEAT_SCHEDULE below).
CELERY_RESULT_EXPIRES = int(os.environ.get("CELERY_RESULT_EXPIRES", str(60 * 60 * 24)))
CELERY_TIMEZONE = TIME_ZONE

# Every Celery task runs on the "background" queue. Extract tasks are not
# Celery tasks: the extract worker (analytics.extract_worker, run by the
# run_extract_worker command) claims them from extract_tasks directly.
CELERY_TASK_DEFAULT_QUEUE = "background"

STALE_TASK_MINUTES = int(os.environ.get("STALE_TASK_MINUTES", "30"))

# How many times manage_processing_task_errors will return an errored extract
# task (status = -1) to pending before giving up on it. Before this existed the
# sweep reset every errored task unconditionally and incremented `attempts`
# with nothing ever reading it, so a task failing for a permanent reason -- a
# missing raster, a geometry the processor cannot handle -- cycled
# -1 -> 0 -> -1 forever, once an hour, indefinitely.
#
# A task at status = -1 whose attempts have reached this is "exhausted": the
# sweep leaves it alone, and _check_request_tasks in manage_user_requests stops
# counting it as pending so a request containing one can still finish, with
# that task's column absent from the output rather than the whole request
# hanging. Deliberately expressed as status + attempts rather than a new
# terminal status value: five call sites read task status, and one missed would
# fail silently as a request waiting forever on work it believes unfinished.
MAX_EXTRACT_TASK_ATTEMPTS = int(os.environ.get("MAX_EXTRACT_TASK_ATTEMPTS", "5"))

# Extract tasks one claim takes: the size of an extract worker's chunk.
#
# The claim asks for the globally highest-priority pending task, and
# extract_tasks is LIST partitioned on dataset_id, so the query cannot name a
# partition: Postgres merge-sorts all 56 partition indexes to return 4 rows.
# Measured on production: ~125ms and ~33k buffer hits per claim. Every one
# runs under pg_advisory_xact_lock, so they are strictly serialized and the
# whole fleet shares a ceiling of roughly 8-15 claims/sec however many
# workers are running.
#
# That makes throughput ~= claims/sec x this number. Going 1 -> 4 took
# production from ~975 to ~3,600 tasks/min, and the claim was still ~79% of
# each message's cost afterwards: actual extraction is ~0.15s/task, so with
# 384 slots there is room for ~2,560 tasks/sec before real work binds.
#
# 4 -> 16 scaled again, to ~14,900 tasks/min, so the claim was still the
# limit there too. Raise it while that holds. The costs of raising it: the
# claim holds the fleet-wide lock a little longer per row it takes, and a
# worker dying abruptly mid-chunk strands up to this many tasks until
# free_stale_processing_tasks reaps them (STALE_TASK_MINUTES). A worker that
# is stopped normally releases the tasks it hadn't started.
EXTRACT_TASK_CLAIM_BATCH = int(os.environ.get("EXTRACT_TASK_CLAIM_BATCH", "64"))

# How long an extract worker slot waits after finding the queue empty (or
# failing to reach the database) before claiming again. Each empty claim
# still merge-sorts every partition's pending index under the claim lock, so
# this keeps an idle fleet from polling the primary hard. It is also the
# longest a new request's tasks wait for an idle worker to notice them.
EXTRACT_WORKER_IDLE_SECONDS = float(os.environ.get("EXTRACT_WORKER_IDLE_SECONDS", "60"))

# Whether processing commits (the batch claim, a task's results and its
# completion) wait for fsync. Off by default. Measured on production
# on 2026-10-02 with the builder stopped: active backends sat in
# LWLock:WALWrite, every database phase of a task rose and fell with WAL
# fsync latency on the Ceph volume while the extract phase stayed flat, and
# extraction itself was ~10ms of a ~60-100ms task.
#
# What async commit risks is small and recoverable. A primary crash loses at
# most ~3 x wal_writer_delay (~600ms) of commits, in WAL order, so a task's
# results and its status are lost together and it simply runs again -- ~10ms
# of work. Any later synchronous commit (a request completing, say) flushes
# every async commit before it, and standbys only receive flushed WAL, so
# nothing durable or visible on a replica can depend on a lost commit. A lost
# claim returns its rows to pending while the worker that claimed them may
# already be running them; another worker can then claim and run them too,
# and a rerun replaces its results wholesale. Set to "1" to restore synchronous commits without a
# deploy.
EXTRACT_TASK_SYNCHRONOUS_COMMIT = (
    os.environ.get("EXTRACT_TASK_SYNCHRONOUS_COMMIT", "0") == "1"
)

# Parallel workers one extract-task build wave fans out to. Each holds a
# pooler connection for an 11-20s INSERT batch, so this trades build-out
# speed against extract throughput -- see _n_extract_task_builders, which
# records the measurements behind this number. Raised 2 -> 4 on 2026-09-23:
# processing now clears tasks 2.5x faster than the builder creates them, so
# the builder, not the queue, is what gates the pipeline long-run.
N_EXTRACT_TASK_BUILDERS = int(os.environ.get("N_EXTRACT_TASK_BUILDERS", "4"))

# Beat interval in seconds, rows per INSERT transaction, and newly created
# tasks per worker invocation (0 means unlimited). The cap is per worker,
# not per wave; the non-global branch has its own invocation budget.
# Batch size controls transaction duration and connection occupancy; the
# worker cap controls total run volume independently. Tune larger batches
# against measured batch duration and extraction throughput (database.md §6).
EXTRACT_TASK_BUILD_INTERVAL_SECONDS = int(os.environ.get("EXTRACT_TASK_BUILD_INTERVAL_SECONDS", "600"))
EXTRACT_TASK_BUILD_BATCH_SIZE = int(os.environ.get("EXTRACT_TASK_BUILD_BATCH_SIZE", "5000"))
EXTRACT_TASK_BUILD_MAX_TASKS = int(os.environ.get("EXTRACT_TASK_BUILD_MAX_TASKS", "0"))
for _name, _minimum in (
    ("EXTRACT_TASK_BUILD_INTERVAL_SECONDS", 1),
    ("EXTRACT_TASK_BUILD_BATCH_SIZE", 1),
    ("EXTRACT_TASK_BUILD_MAX_TASKS", 0),
):
    if globals()[_name] < _minimum:
        raise ImproperlyConfigured(f"{_name} must be at least {_minimum}")

# Whether extract-task build batches wait for fsync. Off by default: the
# database is write-bandwidth bound (backends queue on WALWrite) and these
# build batches are the largest single contributor, while the rows they
# write are speculative and regenerated by the next pass if lost. Set to "1"
# to restore synchronous commits without a deploy.
EXTRACT_TASK_BUILD_SYNCHRONOUS_COMMIT = (
    os.environ.get("EXTRACT_TASK_BUILD_SYNCHRONOUS_COMMIT", "0") == "1"
)
# Snapshot freshness is independent of the extraction/recovery schedules.
STATS_REPORT_INTERVAL_SECONDS = int(os.environ.get("STATS_REPORT_INTERVAL_SECONDS", "3600"))
if STATS_REPORT_INTERVAL_SECONDS < 1:
    raise ImproperlyConfigured("STATS_REPORT_INTERVAL_SECONDS must be at least 1")

CELERY_BEAT_SCHEDULE = {
    # Both sweeps used to be hourly interval schedules, for two reasons that
    # no longer hold. They each ran one unpruned UPDATE over all 57 partitions
    # of extract_tasks -- mean 815s, max 1063s -- so running them often would
    # have meant a 13-minute write transaction holding a pooler server slot
    # several times an hour. Migration 0029's partial indexes took those scans
    # to 6.2s and 0.22s, so the cost argument for an hour is gone.
    #
    # The hour was also expensive in latency. A task stranded at status 2/3
    # waits STALE_TASK_MINUTES (30) to become eligible and then up to another
    # hour for the next tick; request c7501786 spent 63% of its 2h18m wall
    # time on exactly that, with 15,363 of its 15,364 tasks already done.
    # At 10 minutes the worst case drops from ~90 to ~40 minutes, almost all
    # of which is now the staleness threshold rather than the schedule.
    #
    # crontab rather than an interval, deliberately. With fresh Beat state,
    # an interval counts from process start. Deploys that lost the state
    # pushed both sweeps out by up to a full hour -- observed twice during
    # the 0.60.0/0.61.1 rollouts, where neither ran for 44 minutes after the
    # pods restarted.
    # crontab pins them to wall clock, so a restart costs at most one tick.
    #
    # Offset by 5 minutes so they never run together. As interval schedules
    # they shared a tick and contended on the same scan, which is why their
    # runtimes matched to 0.1s across 13 runs. They are cheap now, but there
    # is no reason to overlap them.
    "free-stale-processing-tasks": {
        "task": "analytics.tasks.maintenance.free_stale_processing_tasks",
        "schedule": crontab(minute="*/10"),
    },
    "manage-processing-task-errors": {
        "task": "analytics.tasks.maintenance.manage_processing_task_errors",
        "schedule": crontab(minute="5-59/10"),
    },
    "reset-stale-requests": {
        "task": "analytics.tasks.maintenance.reset_stale_requests",
        "schedule": 3600,
    },
    # Both docs builders are deliberately unscheduled. They never once
    # succeeded in the cluster: DOCS_DIR is unset there, so it falls back to
    # BASE_DIR.parent / "docs" == /app/docs, and /app is a read-only
    # filesystem with no docs directory in the image and no volume mounted
    # over it, so out_dir.mkdir() cannot work. Every night both raised
    #
    #     OSError: [Errno 30] Read-only file system: '/app/docs'
    #
    # and because neither task is in background_metrics.JOBS, there was no
    # JOB_RUNS counter and nothing reported it. The pages went stale at the 2
    # datasets and 6 collections they were first generated with, against 56
    # and 719 in production.
    #
    # Scheduling them is the wrong fix even with a writable path, because the
    # generated pages are tracked in git and the docs site builds from the
    # repo -- output written into a pod filesystem has no consumer. This is a
    # generate-and-commit workflow instead:
    #
    #     DOCS_DIR=<writable> python manage.py build_dataset_docs
    #     DOCS_DIR=<writable> python manage.py build_boundary_docs
    #
    # then commit the result (see the regeneration in PR #48, which also
    # explains why entries can disappear: a renamed dataset or collection
    # changes its slug, so the directories are replaced wholesale rather than
    # merged).
    #
    # To bring the nightly path back, give the worker a writable volume and
    # set DOCS_DIR to it -- and add both tasks to background_metrics.JOBS, so
    # the next failure is visible rather than silent.
    # "build-dataset-docs": {
    #     "task": "datasets.tasks.build_dataset_docs_task",
    #     "schedule": crontab(hour=2, minute=0),
    # },
    # "build-boundary-docs": {
    #     "task": "features.tasks.build_boundary_docs_task",
    #     "schedule": crontab(hour=2, minute=15),
    # },
    "process-user-requests": {
        "task": "analytics.tasks.maintenance.process_user_requests",
        "schedule": crontab(minute="2,7,12,17,22,27,32,37,42,47,52,57"),
    },
    "build-stats-report": {
        "task": "analytics.tasks.maintenance.build_stats_report",
        "schedule": STATS_REPORT_INTERVAL_SECONDS,
        # Runs used to take ~300-400 s on a five-minute schedule, piling up
        # behind any queue stall: on 2026-09-28 ~580 queued behind a scaled-down worker,
        # and when it came back they drained FIFO, ran side by side and
        # saturated pooler-rw. Expiring before the next tick means at most one
        # unstarted message exists; a late one is dropped, not run. The next
        # tick replaces it anyway, and the page keeps serving the old snapshot.
        "options": {"expires": STATS_REPORT_INTERVAL_SECONDS * 0.8},
    },
    "sweep-coverage-records": {
        "task": "analytics.tasks.maintenance.sweep_coverage_records",
        "schedule": crontab(hour=3, minute=0),
    },
    # Deletes results older than CELERY_RESULT_EXPIRES. Celery ships this task
    # but does not schedule it here, so without this entry nothing bounded the
    # result table at all.
    "celery-backend-cleanup": {
        "task": "celery.backend_cleanup",
        "schedule": crontab(hour=4, minute=0),
    },
    "build-extract-tasks": {
        "task": "analytics.tasks.maintenance.build_extract_tasks",
        # Frequent triggers recover interrupted waves; expiry only makes
        # work claimable, it does not dispatch replacement workers. Under
        # the old daily schedule, a deploy killed a wave at 15:44 with 2,503
        # of 2,752 pairs unbuilt and ~12 hours until the next trigger.
        #
        # On 2026-09-24 a rolling deploy killed a wave at 00:07. The old
        # 30-minute stale threshold made it claimable at 00:37, so the hourly
        # :30 tick at 00:30 was too early; nothing built until 01:30, leaving
        # 83 minutes idle. The default 10-minute stale window and 10-minute
        # interval budget ~20 minutes for recovery, before queue/startup delays.
        # Longer intervals deliberately accept a larger recovery delay;
        # a 60-second interval reduces the scheduling portion to one minute.
        #
        # Seconds-based intervals allow arbitrary cadences. Beat preserves
        # last-run times when its schedule state survives; fresh state delays
        # the first trigger by one full interval. That deployment delay is
        # part of the tradeoff when choosing the interval. The wall-clock
        # offsets above belong to the two recovery sweeps, which once ran
        # overlapping scans; the builder has no required offset against them.
        #
        # try_acquire_build_run rejects launches while a wave's heartbeat is
        # fresh. The non-global branch still runs on every trigger; this
        # guarded check plus that branch was measured at 0.6ms in production.
        # Finished/capped waves now release the guard when their last worker
        # exits, even with work left. Crashed waves still need stale recovery.
        "schedule": EXTRACT_TASK_BUILD_INTERVAL_SECONDS,
    },
    "run-user-outreach": {
        "task": "analytics.tasks.maintenance.run_user_outreach",
        "schedule": crontab(hour=6, minute=0, day_of_week=2),
    },
    "sweep-export-gists": {
        "task": "visualize.tasks.sweep_export_gists",
        "schedule": 3600,
    },
    "purge-mcp-oauth-state": {
        "task": "mcp_server.tasks.purge_expired_oauth_state",
        "schedule": 3600,
        # Hourly and idempotent: a run that missed its hour is redundant.
        "options": {"expires": 3000},
    },
}

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
    },
    "formatters": {
        "simple": {
            "format": "{levelname} {name} {message}",
            "style": "{",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "WARNING",
    },
    "loggers": {
        "analytics": {"level": "INFO", "propagate": True},
        "datasets": {"level": "INFO", "propagate": True},
        "features": {"level": "INFO", "propagate": True},
    },
}

# Django REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 100,
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "request_token": os.environ.get("THROTTLE_RATE_REQUEST_TOKEN", "10/hour"),
        "request_submit": os.environ.get("THROTTLE_RATE_REQUEST_SUBMIT", "60/hour"),
        "public_api_anon": os.environ.get("THROTTLE_RATE_PUBLIC_API_ANON", "100/hour"),
        "stac_api_anon": os.environ.get("THROTTLE_RATE_STAC_API_ANON", "100/hour"),
    },
}

# Custom boundary requests are sent as JSON in the request body (not multipart).
# Django's default DATA_UPLOAD_MAX_MEMORY_SIZE is 2.5 MB; raise it to match the
# 50 MB file size limit enforced on the frontend.
DATA_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB

# ── MCP server ───────────────────────────────────────────────────────────────
# A second front end onto this database, served by its own process
# (`manage.py run_mcp`) so chat clients can explore and export GeoQuery data.

# Public URL of the MCP server itself. The OAuth callback and the protected-
# resource metadata are built from it, so it must be the URL the *client*
# reaches -- through a tunnel or ingress, not the container address.
MCP_BASE_URL = os.environ.get("MCP_BASE_URL", "http://localhost:8001")

# This server's client on GeoQuery's own OIDC provider, registered by
# `manage.py ensure_mcp_oidc_client` from these same values. Its one redirect
# URI is {MCP_BASE_URL}/auth/callback, matched exactly.
MCP_OIDC_CLIENT_ID = os.environ.get("MCP_OIDC_CLIENT_ID", "")
MCP_OIDC_CLIENT_SECRET = os.environ.get("MCP_OIDC_CLIENT_SECRET", "")

# Where the MCP *server* reaches the provider for the back-channel calls --
# the token, revocation and JWKS endpoints. Separate from the browser-facing
# URL (FRONTEND_BASE_URL) because a deployment routes the two differently: in
# Kubernetes this is the backend Service, which the MCP pod can reach and the
# browser cannot, while /authorize must be a URL the browser can follow.
MCP_OIDC_INTERNAL_URL = os.environ.get("MCP_OIDC_INTERNAL_URL", "") or FRONTEND_BASE_URL
# Signs the tokens the proxy issues, and derives the encryption key for its
# OAuth state (the mcp_oauth_state table) and the key sealing submit_request's
# confirmation round trip. Must be stable across restarts or every client has
# to re-register, and the same on every replica. Falls back to the OIDC client
# secret when unset.
MCP_JWT_SIGNING_KEY = os.environ.get("MCP_JWT_SIGNING_KEY", "")
# Most connections each MCP process opens for that OAuth state. Opened on
# demand; in production they go through pgBouncer (pooler-tasks), which
# multiplexes every replica's onto its own few server connections.
MCP_STATE_POOL_SIZE = int(os.environ.get("MCP_STATE_POOL_SIZE", "4"))
# Lifetime of the access token the MCP server issues to the chat client.
# Independent of the upstream OIDC access token (one hour): FastMCP
# re-validates and refreshes that on every request, so this only sets how
# often the client has to come back for a new token.
MCP_ACCESS_TOKEN_EXPIRY_SECONDS = int(
    os.environ.get("MCP_ACCESS_TOKEN_EXPIRY_SECONDS", str(30 * 24 * 60 * 60))
)

# Explicitly run the MCP server with no authentication, even if an OIDC
# client is configured. Every caller is then anonymous: public data only, no
# exports. Unlike simply leaving the client credentials unset (which `run_mcp`
# refuses outside DEBUG), this is an operator's deliberate choice and is
# honoured in any environment -- so never set it on a deployment that serves
# catalog-restricted data.
MCP_AUTH_DISABLED = os.environ.get("MCP_AUTH_DISABLED", "False").lower() in (
    "true",
    "1",
    "yes",
    "on",
)

# Response-size guardrails. A chat client has to hold every byte a tool
# returns in the model's context, so these are much tighter than the web
# app's: the answer to "too much data" is a link to /viz, not a bigger
# payload.
MCP_RESULTS_MAX_ROWS = int(os.environ.get("MCP_RESULTS_MAX_ROWS", "200"))
MCP_RESULTS_MAX_COLUMNS = int(os.environ.get("MCP_RESULTS_MAX_COLUMNS", "25"))
MCP_MAP_MAX_FEATURES = int(os.environ.get("MCP_MAP_MAX_FEATURES", "5000"))
MCP_MAP_MAX_BYTES = int(os.environ.get("MCP_MAP_MAX_BYTES", str(3 * 1024 * 1024)))
MCP_MODEL_CONTENT_MAX_BYTES = int(
    os.environ.get("MCP_MODEL_CONTENT_MAX_BYTES", str(512 * 1024))
)
MCP_RESULTS_CSV_MAX_BYTES = int(
    os.environ.get("MCP_RESULTS_CSV_MAX_BYTES", str(5 * 1024 * 1024))
)
# An export this large is almost always a misunderstanding of the selection
# rather than a real intent, and it would occupy the workers for days.
MCP_SUBMIT_MAX_TASKS = int(os.environ.get("MCP_SUBMIT_MAX_TASKS", "250000"))

SPECTACULAR_SETTINGS = {
    "TITLE": "GeoQuery Public API",
    "DESCRIPTION": (
        "Read-only public API for GeoQuery datasets and boundaries. "
        "Currently open during beta; API key authentication will be "
        "required once account-based access launches."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
}
