# Generated by Django 5.2.17 on 2026-10-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('pk', models.CompositePrimaryKey('collection', 'key', blank=True, editable=False, primary_key=True, serialize=False)),
                ('collection', models.TextField()),
                ('key', models.TextField()),
                ('value', models.JSONField()),
                ('ttl', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'mcp_oauth_state',
                'indexes': [models.Index(condition=models.Q(('expires_at__isnull', False)), fields=['expires_at'], name='mcp_oauth_state_expires_idx')],
            },
        ),
    ]
