# Generated by Django 5.2.6 on 2025-12-16 00:45

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shape', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='FeatureCollection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('path', models.CharField(max_length=200, unique=True)),
                ('file_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('file_mask', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('details', models.CharField(blank=True, max_length=1000, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None)),
                ('citation', models.CharField(blank=True, max_length=500, null=True)),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('source_url', models.CharField(blank=True, max_length=200, null=True)),
                ('other', models.JSONField(blank=True, null=True)),
                ('temporal_start', models.DateTimeField(blank=True, null=True)),
                ('temporal_end', models.DateTimeField(blank=True, null=True)),
                ('temporal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('temporal_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_global', models.BooleanField(default=False)),
                ('spatial_extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ingest_src', models.CharField(blank=True, max_length=200, null=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_title', models.CharField(blank=True, max_length=100, null=True)),
                ('group_class', models.CharField(blank=True, max_length=100, null=True)),
                ('group_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'feature_collections',
            },
        ),
        migrations.CreateModel(
            name='FeatMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('attr', models.JSONField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent', null=True, on_delete=django.db.models.deletion.CASCADE, to='features.featmap')),
                ('geom', models.ForeignKey(db_column='geom_id', on_delete=django.db.models.deletion.CASCADE, to='features.feature')),
                ('fc', models.ForeignKey(db_column='fc_id', on_delete=django.db.models.deletion.CASCADE, to='features.featurecollection')),
            ],
            options={
                'db_table': 'feat_map',
                'constraints': [models.UniqueConstraint(fields=('fc', 'geom'), name='feat_map_fc_geom_unique')],
            },
        ),
    ]
