# Generated by Django 6.0.2 on 2026-06-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_matview_add_geom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurecollection',
            name='is_user_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='featurecollection',
            name='upload_metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
