agentContainer: "python:3.11.7"

prod:
  nfs:
    address: 128.239.59.130
    mountPath: /sciclone/nova/test

dev:
  enabled: false
  localDir: /tmp/geoquery-update/


default_image: "jacobwhall/geoquery-backend:c8ba952"
data_root: "/tmp/geoquery-update"


postgis:
  name: "postgis-cluster"
  username: "[POSTGIS USERNAME]"
  password: "[POSTGIS PASSWORD]"
  port: "5432"
  dbname: "geoquery"

email:
  sender: "[EMAIL SENDER]"
  password: "[EMAIL PASSWORD]"
  reply_to: "[EMAIL REPLYTO]"
  server: "smtp.gmail.com"
  port: "587"
  backup_server: "localhost"


documentation:
  devtag: "test"
  request_url: "geoquery.org"

extracts:
  max_tasks: "1000"
  max_workers: "50"
  active_sleep: "5"
  inactive_sleep: "30"
  scale_sleep: "30"

loki:
  loki:
    auth_enabled: false
  minio:
    enabled: true
  serviceMonitor:
    labels:
      release: "prometheus"
  rules:
    labels:
      release: "prometheus"

grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: "Loki"
          type: "loki"
          access: "proxy"
          uid: "P982945308D3682D1"
          url: "http://loki-gateway.{{ .Release.Namespace }}.svc.cluster.local"
        - name: "Postgres"
          type: "postgres"
          uid: "P44368ADAD746BC27"
          url: "postgis-cluster-r.{{ .Release.Namespace }}.svc.cluster.local:5432"
          user: "geoquery"
          secureJsonData:
            password: "dante"
          jsonData:
            database: geoquery
            sslmode: "disable"
        - name: "Prometheus"
          type: "prometheus"
          uid: "PBFA97CFB590B2093"
          url: "http://prometheus-kube-prometheus-prometheus.prometheus.svc.cluster.local:9090"
          
     
