agentContainer: "python:3.11.7"

prod:
  nfs:
    address: 128.239.59.130
    mountPath: /sciclone/nova/test

dev:
  enabled: false
  localDir: /tmp/geoquery-update/

default_image: "jacobwhall/geoquery-backend:6d4b544"

postgis:
  name: "postgis-cluster"
  username: "[POSTGIS USERNAME]"
  password: "[POSTGIS PASSWORD]"

email:
  sender: "[EMAIL SENDER]"
  password: "[EMAIL PASSWORD]"


kube-prometheus-stack:
  kubeControllerManager:
    enabled: false
  kubernetesServiceMonitors:
    enabled: false
  kubeApiServer:
    enabled: false
  kubelet:
    enabled: false
  coreDns:
    enabled: false
  kubeDns:
    enabled: false
  kubeEtcd:
    enabled: false
  kubeScheduler:
    enabled: false
  kubeProxy:
    enabled: false
  kubeStateMetrics:
    enabled: false
  nodeExporter:
    enabled: false

  alertmanager:
    enabled: true

  prometheus:
    enabled: true
    prometheusSpec:
      podMonitorSelectorNilUsesHelmValues: false
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false

  grafana:
    enabled: true
    adminPassword: prom-operator
    defaultDashboardsEnabled: false
    sidecar:
        dashboards:
          enabled: true
