agentContainer: "python:3.11.7"

prod:
  nfs:
    address: 128.239.59.130
    mountPath: /sciclone/nova/test

dev:
  enabled: false
  localDir: /tmp/geoquery-update/

default_image: "jacobwhall/geoquery-backend:6d4b544"

postgis:
  name: "postgis-cluster"
  username: "[POSTGIS USERNAME]"
  password: "[POSTGIS PASSWORD]"

email:
  sender: "[EMAIL SENDER]"
  password: "[EMAIL PASSWORD]"
