FROM python:3.11-bookworm

RUN mkdir geoquery
WORKDIR geoquery

# we should eventually move the python package to one directory for ease of copying
COPY src src
COPY pyproject.toml pyproject.toml

RUN pip install --no-cache-dir .
