FROM python:3.11-bookworm

RUN mkdir geoquery
WORKDIR geoquery

# we should eventually move the python package to one directory for ease of copying
COPY src src
COPY pyproject.toml pyproject.toml

# copy docs over too
COPY docs docs
COPY scripts scripts
COPY mkdocs.yml mkdocs.yml

# use the jwhall user to get around NFS permission nonsense
RUN useradd jwhall -ms /bin/bash -u 220294
RUN groupadd ad-reu -g 9915

# jwhall and ad-reu
USER jwhall:ad-reu

# RUN chown -R jwhall .

# for writing to NFS mounts
RUN groupadd ad-reu -g 9915

RUN pip install --no-cache-dir .
