FROM python:3.11-bookworm

# install vim, sudo
# these are more development-oriented and we should consider removing them in the future
RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    sudo \
    vim \
&& rm -rf /var/lib/apt/lists/*

RUN mkdir geoquery
WORKDIR geoquery

# we should eventually move the python package to one directory for ease of copying
COPY src src
COPY pyproject.toml pyproject.toml

# copy docs over too
COPY docs docs
COPY scripts scripts
COPY mkdocs.yml mkdocs.yml

# for writing to NFS mounts
RUN groupadd ad-reu -g 9915

RUN pip install --no-cache-dir .
