apiVersion: v1
kind: ConfigMap
metadata:
  name: gq-config
  namespace: {{.Release.namespace}}
data:
  devtag: ""
  request_url: "geoquery.org"
  postgis_address: {{ printf "%s-rw.%s.svc.cluster.local" .Values.postgis.name .Release.Namespace }}
  postgis_port: "5432"
  postgis_dbname: "geoquery"
  data_root: "/tmp/geoquery-update"
  email_reply_to: "AidData GeoQuery <geo@aiddata.wm.edu>"
  email_server: "smtp.gmail.com"
  email_port: "587"
  email_backup_server: "localhost"
  extracts_max_tasks: "1000"
  extracts_max_workers: "50"
  extracts_active_sleep: "5"
  extracts_inactive_sleep: "30"
  extracts_scale_sleep: "30"
