apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: {{ .Values.backend_image }}
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "uvicorn src.gqcore.api.main:app --host 0.0.0.0 --port 8000" ]
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: gq-config-vol
          mountPath: /config
        - name: postgis-secret-vol
          mountPath: /secrets/db
      volumes:
      - name: gq-config-vol
        configMap:
          name: gq-config
      - name: postgis-secret-vol
        secret:
          secretName: geoquery-postgis
          optional: true
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000