apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-endpoint-server
  namespace: geoquery-backend-cmhwang
  labels:
    app: api-endpoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-endpoint
  template:
    metadata:
      labels:
        app: api-endpoint
    spec:
      containers:
      - name: api-endpoint
        image: jacobwhall/geoquery-backend:4a21dcc
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "mkdocs serve -a 0.0.0.0:8000 --no-livereload" ]
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-api
spec:
  selector:
    app: endpoint-api
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8000