apiVersion: batch/v1
kind: CronJob
metadata:
  name: errors
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccount: geoquery-super
          serviceAccountName: geoquery-super
          volumes:
          - name: gq-config-vol
            configMap:
              name: gq-config
          - name: postgis-secret-vol
            secret:
              secretName: geoquery-postgis
              optional: true
          - name: email-secret-vol
            secret:
              secretName: geoquery-gmail
              optional: true
          containers:
          - name: extracts
            image: {{.Values.default_image}}
            command: [ "/bin/bash", "-c", "--" ]
            args: [ "python /geoquery/src/gqcore/tasks/manage_errors.py" ]
            volumeMounts:
            - name: gq-config-vol
              mountPath: /config
            - name: postgis-secret-vol
              mountPath: /secrets/db
            - name: email-secret-vol
              mountPath: /secrets/email
