apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        geoquery.org/log-group: backend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend_image }}
