apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: 'true'
  name: {{ .Release.Namespace }}-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - backend:
            service:
              name: docs
              port:
                name: http
          path: /docs/(.*)
          pathType: ImplementationSpecific
        - backend:
            service:
              name: api
              port:
                name: http
          path: /api/(.*)
          pathType: ImplementationSpecific
        - backend:
            service:
              name: frontend
              port:
                name: http
          path: /(.*)
          pathType: ImplementationSpecific
