kind: ServiceAccount
apiVersion: v1
metadata:
  name: init-db-acct
  namespace: {{ .Release.namespace }}

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: init-db-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
    - "postgresql.cnpg.io"
    resources: [clusters/status]
    verbs:
    - "get"

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: init-db-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: init-db-role
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: init-db-acct  # adjust name based on the service account you create

---

apiVersion: batch/v1
kind: Job
metadata:
  name: geoquery-init-db-{{ uuidv4 }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PostSync # run job after all other resources are ready
spec:
  template:
    metadata:
      labels:
        geoquery.org/log-group: backend
    spec:
      serviceAccount: init-db-acct
      serviceAccountName: init-db-acct
      volumes:
      - name: gq-config-vol
        configMap:
          name: gq-config
      - name: postgis-secret-vol
        secret:
          secretName: geoquery-postgis
          optional: true
      containers:
      - name: geoquery-init-db
        image: {{ .Values.default_image }}
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "python /geoquery/src/gqcore/tasks/init_db.py" ]
        volumeMounts:
        - name: gq-config-vol
          mountPath: /config
        - name: postgis-secret-vol
          mountPath: /secrets/db
      restartPolicy: Never
  backoffLimit: 4

