apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoquery-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
{{- $pvname := printf "%s-%s" "geo-datasets" .Release.Name }}
{{- $pvexists := lookup "v1" "persistentvolume" .Release.Namespace $pvname }}
{{- if not $pvexists -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $pvname }}
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: {{ .Release.Namespace }}
    name: geo-datasets-pvc
  {{- toYaml .Values.geo_datasets_volume | nindent 2 }}
{{- end }}
---
{{- $pvcexists := lookup "v1" "PersistentVolumeClaim" .Release.Namespace "geo-datasets-pvc" }}
{{- if not $pvcexists }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geo-datasets-pvc
  annotations:
    "helm.sh/resource-policy": keep
spec:
  storageClassName: {{ .Values.geo_datasets_volume.storageClassName }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Gi
{{- end }}
