apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoquery-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
