apiVersion: v1
kind: Pod
metadata:
  name: python
  namespace: {{.Release.Namespace}}
spec:
  serviceAccount: geoquery-super
  serviceAccountName: geoquery-super
  volumes:
  # - name: geoquery-pv
  #   hostPath:
  #     path: /tmp/geoquery-update
  - name: gq-config-vol
    configMap:
      name: gq-config
  - name: postgis-secret-vol
    secret:
      secretName: geoquery-postgis
      optional: true
  - name: email-secret-vol
    secret:
      secretName: geoquery-gmail
      optional: true
  containers:
  - name: python
    image: {{.Values.default_image}}
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
    volumeMounts:
    # - name: geoquery-pv
    #   mountPath: /tmp/geoquery-update
    - name: gq-config-vol
      mountPath: /config
    - name: postgis-secret-vol
      mountPath: /secrets/db
    - name: email-secret-vol
      mountPath: /secrets/email
