apiVersion: v1
metadata:
  name: geoquery-postgis
  namespace: {{.Release.Namespace}}
kind: Secret
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgis.username | quote }}
  password: {{ .Values.postgis.password | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: geoquery-gmail
  namespace: {{.Release.Namespace}}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.email.sender | quote }}
  password: {{ .Values.email.password | quote }}
