name: Build development image
on:
  push:
    branches:
      - develop
  paths:
    - "src/**"
    - "pyproject.toml"

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get Short Commit SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}

    - name: Buildah Action
      uses: redhat-actions/buildah-build@v2
      with:
        image: geoquery-backend
        tags: ${{ steps.vars.outputs.sha_short }}
        containerfiles: |
          ./k8s/containers/backend/Containerfile
        oci: true

    - name: Push Image
      username: jacobwhall
      password: ${{ secrets.docker_password }}
      registry: docker.io/jacobwhall
      image: geoquery-backend
      tags: ${{ steps.vars.outputs.sha_short }}
